name: Hello world

on:
  push

jobs:

  sit:
    runs-on: ubuntu-latest
    steps:
      - name: SIT Deployment
        run: |
          echo "Deploying to SIT environment"
          echo "Harsha is in the DevOps team"
          echo "hello," ${{vars.GOA_LO_BAMCHIK}}

  stage:
    runs-on: ubuntu-latest
    needs: sit
    steps:
      - name: STAGE Deployment
        run: |
          echo "Deploying to STAGE environment"

  prod:
    runs-on: ubuntu-latest
    needs: stage
    steps:
      - name: TRAIN Deployment
        run: |
          echo "Deploying to TRAIN environment"

  train:
    runs-on: ubuntu-latest
    needs: prod
    steps:
      - name: PROD Deployment
        run: |
          echo "Deploying to PROD environment"
