on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run multiple shell commands
        run: |
          echo "Hey hi, welcome to my world"
          echo "Harsha is in the DevOps team"
          echo "This is a sample workflow"
