on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
        echo "hey hi wecome to my world"
        echo "harsha is a devops team"
        
